; this file is autogenerated on AtsuiKagi launch
if FileExist('plugins/KDEMoverSizer.ahk') {
  #Include plugins/KDEMoverSizer.ahk
  APP.AddLib('KDEMoverSizer', 0)
}
if FileExist('plugins/SwapButtonsHandler.ahk') {
  #Include plugins/SwapButtonsHandler.ahk
  APP.AddLib('SwapButtonsHandler', 0)
}
if FileExist('plugins/TextLocaleManager.ahk') {
  #Include plugins/TextLocaleManager.ahk
  APP.AddLib('TextLocaleManager', 0)
}
if FileExist('plugins/TextToSpeech.ahk') {
  #Include plugins/TextToSpeech.ahk
  APP.AddLib('TextToSpeech', 0)
}
if FileExist('plugins/TimerHandlers.ahk') {
  #Include plugins/TimerHandlers.ahk
  APP.AddLib('TimerHandlers', 0)
}
if FileExist('plugins/TouchGesturesSimulator.ahk') {
  #Include plugins/TouchGesturesSimulator.ahk
  APP.AddLib('TouchGesturesSimulator', 5)
}
if FileExist('plugins/VirtualDesktopManager.ahk') {
  #Include plugins/VirtualDesktopManager.ahk
  APP.AddLib('VirtualDesktopManager', 0)
}
if FileExist('plugins/WindowManager.ahk') {
  #Include plugins/WindowManager.ahk
  APP.AddLib('WindowManager', 0)
}
